language: node_js
node_js:
  - "8"

os:
  - linux
#  - osx
dist: trusty # to use Ubuntu 14.04
#osx_image: xcode8.3 # to use macOS Sierra 10.12
sudo: false

git:
  depth: 3

branches:
  only: master

env:
  global:
    - secure: loearYx7bUius1TLj/wQULubiQwrxO0NmE9IyLXZ/blBDtK3cC6XEU5ILfP1jHZKQ5jBePGE3UEmY/e6mPbtrPth1Pbr9dmSPu7l9/wRmSRcVbjSE5uxRfzG1rBkzVaS+ilk2kjYGflYV6SZPJykSP/iWCcc95siEmQeuNIzo90y2ux8+4r/5xCv4BEiVtdu3E0SX5WgmwcI9h/Ztl2Rt3sRtpxOLidu0RuSl+J1PbOIfG7OR1FOcDjXXWdNhawMVeOYvQI+Wfbm/ogvgXBG9Tap7UKjmT3Co65I/xjGwXgryXfRLx2Pf005yQDtio6QUVrNvYdjgxnSzjGaCXr6KPCd1HIWOcEVYzWwid5H/eBuLtpEGqyQgHVOVwjx+Ul6tFjxPhgtpUrDB2/perVIcehFDbvBABOZNUmpAOI1quz0174rskdd+eMAxCAQcU4pZbMKa2/WJi+LG9T9heLad3ckIN1ot6txqToZ6EstxRahwYBUwuiX0SBHdb96IhsDnGWmRZaxEOD4o4Rf1MPk/0CVwY+3n0ah+NV6njq5fbcGkqHG8kDSI1CS8xwAKKzl5jM2QtuNJN6Y3DIPhutn3xp6NDQQvsYCJZeoTn3BeORunMn7z7bZt+hdJtORTUGW1tm8Hyehyx4Ofwn8oH98HODX9rIXXzFP8+vi1fqS4QM= # CODECLIMATE
    - secure: GUJeTIIwtr9S8LvRIjiK8YwMJG36jq7E0QLP1F8q2CStGkTWbPYkQ2feZexE6PIeWB32nWJOmdkmqJzeol6LFNPT7Tzm2nCrxf7diBLGf9rcrqD6F/aUdJD+Itf/LZecRWM3yf5dP4R45MzyKSgvX/9zFzRjNMFTP6j5XUoCt+hBI4miL8A897aktT+Sg9hxB901rC21RU2b6r8ByprroJK3W34QDiK6AK3Wira378apNoZn2WhYotsmEOiv4iSzbT/6TkXfrWJbTzFedwH87ZT6ABFS7sLrVYNlU+tbDYke3GhyC0bYeOx1mYpRcSvDa3Em788xqBOs+OE6wao8oHCU983/calPIlVobqtfkzO8z31AKkuCPOEgTKNo84azrunvlWven/MLseTwgYXEgxeS6rBW/v3X3ILg9TWIkxLX6L9lKImKtQ6znGq2FppnmzjsG4rfyYS94hVvdO6ouQaIxrRPgxDc+DbWRQuw854PT2PYKIK7XCZ8x38zCeR1qgLLeVKgIop5W8DGgz27DdA/0WIvK5fZiN7sBZL5spGUnvU72Mf37jNhO8DKJyUH0PQnhBxJvbbta+a3wanblMm2d/E6K5iZdv6DuBuYfvwpzjl5U37XcxPPu5eA/xW4NRHww6SPpiRuXpdDIDJTv9Wtyb6GdlHt7cQojJM+xaw= # COVERALLS

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
      organization: "ks89-github"
      token:
        secure: "qeRl/C/3Tl4disBqCY0M5DHCh0l9+wOJPTcyknIYx+0PMcpZM5JxUjKFxoJ55HqZ2OZxZRPCaC94yP3V2Paf+1sNouulQLLL0AmZfMvwAkmRpHgQDLTA14td6UW2CUcBMMTPZAF9JN0vemI2oEXAGG5aNbM7HrNLOurG4jyuljNkVvp1vR4Opx0fmCgpChnhVA+1gvzZwLrWg2cSNaXIkDD98x0w6tiEeVn76IcZXz5NmyDCFxaQHSn5yQQ7oYxfag/9Cc33zEPfGARkAalXkSpGNNVS5ANDUIiuga2OcyFmY306M6Wsw22XQV+XAFFtuIEXJG4HVAHSaBLHeDm499Pw8LRZ/hUnNTp6oHzkP6GPPYWLTac8cBnGPIfqcDU4DqdflA/OQzhTXXZ/cFrMjRT2kksN/HUQY6AWbNNqSPD5HG65pkUyUhhrKGEpaSsfWAECpHlNC/LC2w6GwykPT3JoE2Aytr6KQ9ooS6mwvRRUXRrwZsw8zXqWSxRfimwkeu5OzpSu1Eeeaf66dYFcMGs1FdzZLikijUjIs7NNLv5kioqE5J60g6L73qgVpJoUDALG8PFMA7ITDJP04ii/tB9CU5HqCnKgdnzfMkFN59LDRJAgIZLgkFLRk7l96xxkWkdqLRkps7k0iiTBUa6961Clk9xWLHKA1+xfD8sIoYU="
jdk:
  - oraclejdk8

matrix:
  fast_finish: true


before_install:
  - source travisci/before_install.sh
install:
  - bash travisci/install.sh
after_install:
  - npm rebuild node-sass
before_script:
  - source travisci/before_script.sh # starts in the same shell
script:
  - bash travisci/script.sh
after_success:
  - source travisci/after_success.sh
#after_script:
#  - bash travisci/after_script.sh

cache:
  apt: true
  bundler: true
  directories:
    - ./node_modules
    - '$HOME/.sonar/cache'
