language: node_js
node_js:
  - "10"

os:
  - linux
dist: trusty

# temporary fix to prevent an issue related to chrome headless. I should restore this to false as soon as possible.
# also I should remove these 2 commands from before_script
# 1. sudo chown root /opt/google/chrome/chrome-sandbox
# 2. sudo chmod 4755 /opt/google/chrome/chrome-sandbox
sudo: true

git:
  depth: 3

branches:
  only: master

env:
  global:
    - secure: loearYx7bUius1TLj/wQULubiQwrxO0NmE9IyLXZ/blBDtK3cC6XEU5ILfP1jHZKQ5jBePGE3UEmY/e6mPbtrPth1Pbr9dmSPu7l9/wRmSRcVbjSE5uxRfzG1rBkzVaS+ilk2kjYGflYV6SZPJykSP/iWCcc95siEmQeuNIzo90y2ux8+4r/5xCv4BEiVtdu3E0SX5WgmwcI9h/Ztl2Rt3sRtpxOLidu0RuSl+J1PbOIfG7OR1FOcDjXXWdNhawMVeOYvQI+Wfbm/ogvgXBG9Tap7UKjmT3Co65I/xjGwXgryXfRLx2Pf005yQDtio6QUVrNvYdjgxnSzjGaCXr6KPCd1HIWOcEVYzWwid5H/eBuLtpEGqyQgHVOVwjx+Ul6tFjxPhgtpUrDB2/perVIcehFDbvBABOZNUmpAOI1quz0174rskdd+eMAxCAQcU4pZbMKa2/WJi+LG9T9heLad3ckIN1ot6txqToZ6EstxRahwYBUwuiX0SBHdb96IhsDnGWmRZaxEOD4o4Rf1MPk/0CVwY+3n0ah+NV6njq5fbcGkqHG8kDSI1CS8xwAKKzl5jM2QtuNJN6Y3DIPhutn3xp6NDQQvsYCJZeoTn3BeORunMn7z7bZt+hdJtORTUGW1tm8Hyehyx4Ofwn8oH98HODX9rIXXzFP8+vi1fqS4QM= # CODECLIMATE
    - secure: GUJeTIIwtr9S8LvRIjiK8YwMJG36jq7E0QLP1F8q2CStGkTWbPYkQ2feZexE6PIeWB32nWJOmdkmqJzeol6LFNPT7Tzm2nCrxf7diBLGf9rcrqD6F/aUdJD+Itf/LZecRWM3yf5dP4R45MzyKSgvX/9zFzRjNMFTP6j5XUoCt+hBI4miL8A897aktT+Sg9hxB901rC21RU2b6r8ByprroJK3W34QDiK6AK3Wira378apNoZn2WhYotsmEOiv4iSzbT/6TkXfrWJbTzFedwH87ZT6ABFS7sLrVYNlU+tbDYke3GhyC0bYeOx1mYpRcSvDa3Em788xqBOs+OE6wao8oHCU983/calPIlVobqtfkzO8z31AKkuCPOEgTKNo84azrunvlWven/MLseTwgYXEgxeS6rBW/v3X3ILg9TWIkxLX6L9lKImKtQ6znGq2FppnmzjsG4rfyYS94hVvdO6ouQaIxrRPgxDc+DbWRQuw854PT2PYKIK7XCZ8x38zCeR1qgLLeVKgIop5W8DGgz27DdA/0WIvK5fZiN7sBZL5spGUnvU72Mf37jNhO8DKJyUH0PQnhBxJvbbta+a3wanblMm2d/E6K5iZdv6DuBuYfvwpzjl5U37XcxPPu5eA/xW4NRHww6SPpiRuXpdDIDJTv9Wtyb6GdlHt7cQojJM+xaw= # COVERALLS
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  fast_finish: true


before_install:
  - source travisci/before_install.sh
install:
  - bash travisci/install.sh
after_install:
  - npm rebuild node-sass
before_script:
  - source travisci/before_script.sh # starts in the same shell
script:
  - bash travisci/script.sh
after_success:
  - source travisci/after_success.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  apt: true
  bundler: true
  directories:
    - ./node_modules
    - ./servers/node-express-js/node_modules
    - ./servers/node-express-ts/node_modules
    - ./servers/node-koa-js/node_modules
    - '$HOME/.sonar/cache'
